apiVersion: v1
kind: Secret
metadata:
  name: satellite-secret
  namespace: satellite
type: Opaque
stringData:
  POSTGRES_DB: satellite
  POSTGRES_USER: satellite
  POSTGRES_PASSWORD: satellite
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
